services:
  - type: web
    name: ims-api-prod
    env: docker
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    region: frankfurt
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false

