export const PERMISSION_CODES = {
  INVENTORY_READ: 'INVENTORY.READ',
  INVENTORY_WRITE: 'INVENTORY.WRITE',
  INVENTORY_COUNT: 'INVENTORY.COUNT',
  PROCUREMENT_READ: 'PROCUREMENT.READ',
  PROCUREMENT_WRITE: 'PROCUREMENT.WRITE',
  RECIPE_READ: 'RECIPE.READ',
  RECIPE_WRITE: 'RECIPE.WRITE',
  SALES_IMPORT: 'SALES.IMPORT',
  SALES_READ: 'SALES.READ',
  REPORTING_READ: 'REPORTING.READ',
  ADMIN_USERS: 'ADMIN.USERS',
  ADMIN_ROLES: 'ADMIN.ROLES',
  ADMIN_TENANTS: 'ADMIN.TENANTS',
  ADMIN_FEATURE_FLAGS: 'ADMIN.FEATURE_FLAGS',
} as const;
export type PermissionCode = (typeof PERMISSION_CODES)[keyof typeof PERMISSION_CODES];
