// Auto-generated by: pnpm generate:types
// Run this command after authenticating with the Supabase CLI
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = Record<string, unknown>;
export type Tables<T extends string> = Record<string, unknown>;
export type TablesInsert<T extends string> = Record<string, unknown>;
export type TablesUpdate<T extends string> = Record<string, unknown>;
